File:
  description: A file included in the research project, such as a text file, script file, or images.
  props:
    "@id":
      expected_type: str
      example: config/setting.txt
      required: Required.
      description: MUST be either a URI Path relative to the RO-Crate root directory or an absolute URI that is directly downloadable. If the file originates outside the repository, @id SHOULD allow for simple retrieval (e.g., HTTP GET), including redirections and HTTP/HTTPS authentication. RO-Crate metadata (ro-crate-metadata.json) is excluded.
    name:
      expected_type: str
      example: setting.txt
      required: Required.
      description: Denotes the file name.
    contentSize:
      expected_type: str
      example: 1560B
      required: Required.
      description: MUST be an integer representing the file size, suffixed with `B` for bytes. Other units like "KB", "MB", "GB", "TB", and "PB" may also be used if necessary.
    encodingFormat:
      expected_type: str
      example: text/plain
      required: Optional.
      description: MUST be a MIME type, excluding any "x-" prefix. Specifies the file format.
    sha256:
      expected_type: str
      example: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
      required: Optional.
      description: MUST be the SHA-2 SHA256 hash of the file.
    url:
      expected_type: str
      example: https://github.com/username/repository/file
      required: Optional.
      description: MUST be a direct URL link to the file.
    sdDatePublished:
      expected_type: str
      example: "2022-12-01"
      required: Required when the file is sourced from outside the RO-Crate Root.
      description: Indicates the date the file was obtained. MUST be a string in ISO 8601 date format.
Dataset:
  description: A folder containing files included in the research project.
  props:
    "@id":
      expected_type: str
      example: config/
      required: Required.
      description: MUST be either a URI Path relative to the RO-Crate root (as stated in the identifier property of RootDataEntity) or an absolute URI. MUST end with `/`. This indicates the path to the directory.
    name:
      expected_type: str
      example: config
      required: Required.
      description: Denotes the directory name.
    url:
      expected_type: str
      example: https://github.com/username/repository/directory
      required: Optional.
      description: MUST be a direct URL link to the directory.
Organization:
  description: An entity associated with the research project, such as a university, research institution, or funding agency.
  props:
    "@id":
      expected_type: str
      example: https://ror.org/04ksd4g47
      required: Required.
      description: MUST be the URL representing the organization. Use of ROR ID is recommended.
    name:
      expected_type: str
      example: National Institute of Informatics
      required: Required.
      description: The official name of the organization.
    alias:
      expected_type: str
      example: NII
      required: Optional.
      description: An alternative or abbreviated name for the organization.
    description:
      expected_type: str
      example: Japan's only comprehensive research institution striving to innovate in the field of informatics.
      required: Optional.
      description: A brief description of the organization.
Person:
  description: An individual contributing to the research project, such as a researcher.
  props:
    "@id":
      expected_type: str
      example: https://orcid.org/0000-0001-2345-6789
      required: Required.
      description: MUST be a URL representing the individual. Use of ORCID ID is recommended.
    name:
      expected_type: str
      example: Ichiro Suzuki
      required: Required.
      description: The full name of the person. MUST follow the format of first name followed by family name.
    alias:
      expected_type: str
      example: S. Ichiro
      required: Optional.
      description: An alternative or abbreviated name for the person.
    affiliation:
      expected_type: Organization
      example: '{"@id": "https://ror.org/04ksd4g47"}'
      required: Required.
      description: The organization to which the person is affiliated. MUST be a dictionary containing the @id of the Organization entity.
    email:
      expected_type: str
      example: ichiro@example.com
      required: Required.
      description: The email address of the person.
    telephone:
      expected_type: str
      example: "03-0000-0000"
      required: Optional.
      description: The phone number of the person. Hyphens can be used as separators.
License:
  description: A license applied to the dataset.
  props:
    "@id":
      expected_type: str
      example: "https://www.apache.org/licenses/LICENSE-2.0"
      required: Required.
      description: MUST be the URL representing the license.
    name:
      expected_type: str
      example: Apache License 2.0
      required: Required.
      description: The official name of the license.
    description:
      expected_type: str
      example: The license as defined by the Apache Software Foundation.
      required: Optional.
      description: A brief explanation of the license.
RepositoryObject:
  description: A repository in which the research data is stored and managed.
  props:
    "@id":
      expected_type: str
      example: "https://doi.org/xxxxxxxx"
      required: Required.
      description: MUST be the URI of the repository. If accessible via URL, use of DOI link is recommended.
    name:
      expected_type: str
      example: Gakunin RDM
      required: Required.
      description: The name of the repository.
    description:
      expected_type: str
      example: A repository managed by NII.
      required: Optional.
      description: A brief summary of the repository.
DataDownload:
  description: A downloadable dataset associated with the research project.
  props:
    "@id":
      expected_type: str
      example: https://zenodo.org/record/example
      required: Required.
      description: MUST be an accessible URL.
    description:
      expected_type: str
      example: All dataset available at this URL as a zip file.
      required: Optional.
      description: A brief explanation about the download.
    sha256:
      expected_type: str
      example: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
      required: Optional.
      description: MUST be the SHA-2 SHA256 hash of the downloadable file.
    uploadDate:
      expected_type: str
      example: "2022-12-01"
      required: Optional.
      description: MUST be in ISO 8601 date format. Indicates the date when the dataset was uploaded to this site.
HostingInstitution:
  # based on Organization entity
  description: An organization tasked with managing research data.
  props:
    "@id":
      expected_type: str
      example: https://ror.org/04ksd4g47
      required: Required.
      description: MUST be the URL of the organization. Use of ROR ID is recommended.
    name:
      expected_type: str
      example: National Institute of Informatics
      required: Required.
      description: The official name of the organization.
    description:
      expected_type: str
      example: Japan's premier academic research institution striving to pioneer new fields in informatics.
      required: Optional.
      description: A brief overview of the organization.
    address:
      expected_type: str
      example: "2-1-2 Hitotsubashi, Chiyoda-ku, Tokyo, Japan, 101-8430"
      required: Required.
      description: The physical location of the organization.
ContactPoint:
  description: Contact information details.
  props:
    "@id":
      expected_type: str
      example: "#mailto:contact@example.com"
      required: Required.
      description: MUST be an email prefixed with `#mailto:` or a phone number prefixed with `#callto:`.
    name:
      expected_type: str
      example: Sample Inc., Open-Science department, data management unit
      required: Required.
      description: The name of the person or department responsible for data set management.
    email:
      expected_type: str
      example: contact@example.com
      required: Either email or telephone is required (see following section for telephone).
      description: The email address for contacting the responsible party.
    telephone:
      expected_type: str
      example: "03-0000-0000"
      required: Either email (as described in previous section) or telephone is required.
      description: The telephone number for contacting the responsible party.
