version: '3.5'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile-dev
    image: nii-dg
    container_name: nii-dg
    volumes:
      - ${PWD}:/app
    restart: on-failure
    working_dir: /app
    ports:
      - 5000:5000
    command: ['sleep', 'infinity']
    networks:
      - nii-dg


# --- Fork section ---
# This section is from sapporo-service, see https://github.com/sapporo-wes/sapporo-service/blob/main/docker-compose.yml
# Original license: https://github.com/sapporo-wes/sapporo-service/blob/main/LICENSE
  sapporo:
    image: ghcr.io/sapporo-wes/sapporo-service:1.4.9
    container_name: sapporo-service
    volumes:
      # The ones below are mounted for cwltool and DinD.
      - ${PWD}/run:${PWD}/run
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp:/tmp
    environment:
      # Priority: [Command Line Argument] -> [Environment Variable] -> [Default Values]
      # - SAPPORO_HOST=0.0.0.0 # Not available when using the uwsgi server.
      # - SAPPORO_PORT=1122 # Not available when using the uwsgi server.
      - SAPPORO_DEBUG=False
      - SAPPORO_RUN_DIR=${PWD}/run
      # - SAPPORO_DATA_REMOVE_OLDER_THAN_DAYS=30
      # - SAPPORO_GET_RUNS=False
      # - SAPPORO_RUN_ONLY_REGISTERED_WORKFLOWS=False
      # - SAPPORO_ACCESS_CONTROL_ALLOW_ORIGIN=*
      # - SAPPORO_URL_PREFIX=/
    ports:
      - 0.0.0.0:1122:1122
    restart: on-failure
    working_dir: /app
    command:
      [
        "uwsgi",
        "--yaml",
        "/app/uwsgi.yml",
        "--http",
        "0.0.0.0:1122",
        "--workers",
        "1" # Number of workers to process http requests
      ]
    networks:
      - sapporo
# --- End fork section ---
      - nii-dg

networks:
  nii-dg:
    name: nii-dg-network
  sapporo:
    name: sapporo-network
