version: "3.5"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile-dev
    image: nii-dg-dev
    container_name: nii-dg-dev
    volumes:
      - ${PWD}:/app
    environment:
      # Basically, these variables are set in Dockerfile and module as default values.
      - DG_HOST=0.0.0.0
      - DG_PORT=5000
      - DG_USE_EXTERNAL_CTX=False
      - DG_ALLOW_OTHER_GH_REPO=False
      - DG_WSGI_SERVER=flask
      - DG_WSGI_THREADS=1
    restart: on-failure
    working_dir: /app
    ports:
      - 0.0.0.0:5000:5000
    command: [ "sleep", "infinity" ]
