version: "3.5"
services:
  app:
    image: ghcr.io/nii-dg/nii-dg:0.1.2
    container_name: nii-dg
    volumes:
      - ${PWD}:/app
    environment:
      # Basically, these variables are set in module as default values.
      - DG_HOST=0.0.0.0
      - DG_PORT=5000
      - DG_USE_EXTERNAL_CTX=False
      - DG_ALLOW_OTHER_GH_REPO=False
      - DG_WSGI_SERVER=waitress
      - DG_WSGI_THREADS=1
    restart: on-failure
    working_dir: /app
    ports:
      - 0.0.0.0:5000:5000
    command: [ "python", "/app/nii_dg/api.py" ]
