openapi: "3.0.0"
info:
  title: "NII-DG Data Governance REST API"
  version: "1.0.0"
  description: "This API facilitates data governance operations within research contexts."
  license:
    name: "Apache 2.0"
    url: "https://raw.githubusercontent.com/NII-DG/nii-dg/main/Licence.txt"
paths:
  /validate:
    post:
      summary: "Validate RO-Crate with NII-DG Library"
      description: "Validate an RO-Crate either created using the NII-DG library or compatible with the NII-DG schema. Supply the RO-Crate in the request body. To validate specific entities only, add their IDs to the query parameters."
      responses:
        200:
          $ref: "#/components/responses/RequestIdResponse"
        400:
          $ref: "#/components/responses/BadRequest"
        500:
          $ref: "#/components/responses/InternalServerError"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ROCrate"
      parameters:
        - $ref: "#/components/parameters/entityIds"
  /{requestId}:
    get:
      summary: "Fetch Validation Results"
      description: "Retrieve the status and results of a validation request based on a specified request ID."
      responses:
        200:
          $ref: "#/components/responses/ResultResponse"
        400:
          $ref: "#/components/responses/BadRequest"
        500:
          $ref: "#/components/responses/InternalServerError"
      parameters:
        - $ref: "#/components/parameters/requestId"
  /{requestId}/cancel:
    post:
      summary: "Cancel Validation Procedure"
      description: "Initiate a cancellation request for an ongoing validation procedure."
      responses:
        200:
          $ref: "#/components/responses/RequestIdResponse"
        400:
          $ref: "#/components/responses/BadRequest"
        500:
          $ref: "#/components/responses/InternalServerError"
      parameters:
        - $ref: "#/components/parameters/requestId"
  /healthcheck:
    get:
      summary: "Health Check Endpoint"
      description: "Returns `OK` if the application server is functioning properly."
      responses:
        200:
          $ref: "#/components/responses/HealthCheck"
        500:
          $ref: "#/components/responses/InternalServerError"
components:
  schemas:
    RequestId:
      type: string
      format: uuid
      example: 7755fb3d-09f1-46e0-ac6e-d88e4d82cb05
    RequestIdResponse:
      type: object
      properties:
        requestId:
          $ref: "#/components/schemas/RequestId"
    ROCrate:
      type: object
      additionalProperties: true
      description: "RO-Crate object. The schema is dependent on the NII-DG library."
      example:
        {
          "@context": "https://w3id.org/ro/crate/1.1/context",
          "@graph":
            [
              {
                "@id": "ro-crate-metadata.json",
                "@type": "CreativeWork",
                "conformsTo": { "@id": "https://w3id.org/ro/crate/1.1" },
                "about": { "@id": "./" },
              },
              {
                "@id": "./",
                "@type": "Dataset",
                "hasPart": [],
                "name": "example research project",
                "datePublished": "2023-01-20T02:35:21.875+00:00",
                "@context": "https://raw.githubusercontent.com/ascade/nii_dg/develop/schema/context/base/RootDataEntity.json",
              },
            ],
        }
    EntityId:
      type: string
      example: "path/to/file"
    EntityIds:
      nullable: true
      type: array
      items:
        $ref: "#/components/schemas/EntityId"
    ValidationRequest:
      type: object
      properties:
        roCrate:
          $ref: "#/components/schemas/ROCrate"
        entityIds:
          $ref: "#/components/schemas/EntityIds"
    ValidationStatus:
      type: string
      enum:
        - UNKNOWN
        - QUEUED
        - RUNNING
        - COMPLETE
        - FAILED
        - EXECUTOR_ERROR
        - CANCELING
        - CANCELED
    ValidationResult:
      type: object
      properties:
        entityId:
          $ref: "#/components/schemas/EntityId"
        prop:
          type: string
          example: "amed.File:remoteLocation"
        reason:
          type: string
          example: Unable to fetch remote URL.
    ResultResponse:
      description: "The result of the validation procedure. The result schema is dictated by the NII-DG library."
      type: object
      properties:
        requestId:
          $ref: "#/components/schemas/RequestId"
        request:
          $ref: "#/components/schemas/ValidationRequest"
        status:
          $ref: "#/components/schemas/ValidationStatus"
        results:
          type: array
          items:
            $ref: "#/components/schemas/ValidationResult"
    BadRequest:
      type: object
      properties:
        message:
          type: string
          example: Invalid request format.
    NotFound:
      type: object
      properties:
        message:
          type: string
          example: Requested path not found.
    InternalServerError:
      type: object
      properties:
        message:
          type: string
          example: Server encountered an error.
    HealthCheck:
      type: object
      properties:
        message:
          type: string
          example: OK.
          description: Status of the service.
  responses:
    RequestIdResponse:
      description: "Response contains the request ID."
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/RequestIdResponse"
    ResultResponse:
      description: "Response includes validation results."
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ResultResponse"
    BadRequest:
      description: "Response to an incorrectly formatted request."
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/BadRequest"
    NotFound:
      description: "Response to a request for a non-existing path."
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/NotFound"
    InternalServerError:
      description: "Response to a server-side error."
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/InternalServerError"
    HealthCheck:
      description: "Health status of the service."
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/HealthCheck"
  parameters:
    entityIds:
      name: entityIds
      in: query
      description: "List of entity IDs for selective validation. If not provided, all entities in the RO-Crate will be validated."
      required: false
      schema:
        $ref: "#/components/schemas/EntityIds"
      example:
        - "path/to/file"
        - "https://example.com/path/to/file"
    requestId:
      name: requestId
      in: path
      description: "Identifier for the validation request."
      required: true
      schema:
        $ref: "#/components/schemas/RequestId"
