openapi: 3.0.0
info:
  title: "NII-DG Core API"
  version: "1.0.0"
  description: API to perform data governance of research
#   contact:
#     name: Contact Name
#     email: contact@example.com
#     url: https://example.com/
# tags:
#   - name: Metadata
#     description: Metadata related requests
# servers:
#   - url: https://example.com
paths:
  /crates:
    post:
      summary: Validate ro-crate of NII schema
      # tags: [ 'Metadata' ]
      responses:
        '200':
          description: Successfully accepted the request of ro-crate validation and returned request ID.
          content:
            application/json:
              schema:
                type: object
                properties:
                  requestId:
                    type: string
        '400':
          $ref: '#/components/responses/400Error'
      requestBody:
       required: true
       content:
        application/json:
         schema:
          type: string
          format: binary
  /crates/{requestId}:
    get:
      summary: Get result of crate validation
      responses:
        '200':
          description: Successfully get the result of ro-crate validation.
          content:
            application/json:
              schema:
                type: object
                required:
                  - "status"
                properties:
                  status:
                    type: string
                  results:
                    type: object
        '400':
          $ref: '#/components/responses/400Error'
      parameters:
        - $ref: '#/components/parameters/RequestId'
  /crates/{requestId}/status:
    get:
      summary: Get status of validation request
      responses:
        '200':
          description: Successfully get the status of ro-crate validation.
          content:
            application/json:
              schema:
                type: object
                required:
                  - "status"
                  - "requestId"
                properties:
                  status:
                    type: string
                  requestId:
                    type: string
        '400':
          $ref: '#/components/responses/400Error'
    parameters:
        - $ref: '#/components/parameters/RequestId'
  /crates/{requestId}/cancel:
    get:
      summary: cancel validation request
      responses:
        '200':
          description: Successfully canceled the ro-crate validation.
          content:
            application/json:
              schema:
                type: object
                required:
                  - "status"
                  - "requestId"
                properties:
                  status:
                    type: string
                  requestId:
                    type: string
        '400':
          $ref: '#/components/responses/400Error'
    parameters:
        - $ref: '#/components/parameters/RequestId'
  /crates/entities:
    post:
      summary: Validate ro-crate of NII schema partially
      # tags: [ 'Metadata' ]
      responses:
        '200':
          description: Successfully accepted the request of partial ro-crate validation and returned request ID.
          content:
            application/json:
              schema:
                type: object
                properties:
                  requestId:
                    type: string
        '400':
          $ref: '#/components/responses/400Error'
      parameters:
        - name: entityID
          in: query
          required: true
          schema:
            type: string
      requestBody:
       required: true
       content:
        application/json:
         schema:
          type: string
          format: binary
  /crates/entities/{requestId}:
    get:
      summary: Get result of crate partial validation
      responses:
        '200':
          description: Successfully get the result of ro-crate partial validation.
          content:
            application/json:
              schema:
                type: object
                required:
                  - "status"
                  - "entityId"
                properties:
                  status:
                    type: string
                  entityId:
                    type: string
                  results:
                    type: object
        '400':
          $ref: '#/components/responses/400Error'
    parameters:
        - $ref: '#/components/parameters/RequestId'
  /crates/entities/{requestId}/status:
    get:
      summary: Get status of validation request
      responses:
        '200':
          description: Successfully get the status of ro-crate partial validation.
          content:
            application/json:
              schema:
                type: object
                required:
                  - "status"
                  - "entityId"
                properties:
                  status:
                    type: string
                  entityId:
                    type: string
        '400':
          $ref: '#/components/responses/400Error'
    parameters:
        - $ref: '#/components/parameters/RequestId'
  /crates/entities/{requestId}/cancel:
    get:
      summary: cancel partial validation request
      responses:
        '200':
          description: Successfully canceled the ro-crate partial validation.
          content:
            application/json:
              schema:
                type: object
                required:
                  - "status"
                  - "entityId"
                  - "requestId"
                properties:
                  status:
                    type: string
                  entityId:
                    type: string
                  requestId:
                    type: string
        '400':
          $ref: '#/components/responses/400Error'
    parameters:
        - $ref: '#/components/parameters/RequestId'
  /health:
    get:
      summary: for health check
      responses:
        '200':
          description: Successfully accessed to API server.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
components:
  responses:
    400Error:
      description: Invalid request
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
  parameters:
    RequestId:
      name: requestId
      in: path
      required: true
      schema:
        type: string
