#!/usr/bin/env python3
# coding: utf-8

import json

from nii_dg.ro_crate import ROCrate
from nii_dg.schema.base import HostingInstitution, RepositoryObject
from nii_dg.schema.cao import DMP, DMPMetadata, File, Person
from nii_dg.schema.ginfork import File as GinFile
from nii_dg.schema.ginfork import GinMonitoring


def main() -> None:
    ro_crate = ROCrate()
    ro_crate.root["name"] = "example research project"

    org = HostingInstitution("https://www.nii.ac.jp/",
                             {"name": "National Institute of Informatics", "address": "Tokyo Japan"})
    creator = Person("https://example.com/person",
                     {"name": "Ichiro Suzuki", "affiliation": org, "email": "ichiro@example.com"})
    repo = RepositoryObject("https://example.com/repository", {"name": "sample repository"})

    dmp_1 = DMP(1, {
        "name": "execution results",
        "description": "Files generated by execution of workflow.",
        "creator": [creator],
        "keyword": "Informatics",
        "accessRights": "metadata only access",
        "repository": repo,
        "hostingInstitution": org,
        "dataManager": creator})

    dmp_meta = DMPMetadata(props={
        "name": "execution results",
        "about": ro_crate.root,
        "funder": org,
        "keyword": "Informatics",
        "hasPart": [dmp_1]})

    file_cao = File("file_1.txt",
                    {"name": "Sample File", "contentSize": "156GB", "dmpDataNumber": dmp_1})
    file_gin = GinFile("file_1.txt",
                       {"name": "Sample File", "contentSize": "156GB", "experimentPackageFlag": True})
    gin = GinMonitoring(1,
                        {"about": ro_crate.root, "contentSize": "1TB", "workflowIdentifier": "basic", "datasetStructure": "with_code"})

    ro_crate.add(org, creator, repo, dmp_1, dmp_meta, file_cao, file_gin, gin)

    print(json.dumps(ro_crate.as_jsonld(), indent=2))


if __name__ == "__main__":
    main()

"""
{
  "@context": "https://w3id.org/ro/crate/1.1/context",
  "@graph": [
    {
      "@id": "./",
      "@type": "Dataset",
      "hasPart": [
        {
          "@id": "file_1.txt"
        }
      ],
      "name": "example research project",
      "dateCreated": "2023-01-20T02:35:21.875+00:00",
      "@context": "https://raw.githubusercontent.com/ascade/nii_dg/develop/schema/context/base/RootDataEntity.json"
    },
    {
      "@id": "ro-crate-metadata.json",
      "@type": "CreativeWork",
      "conformsTo": {
        "@id": "https://w3id.org/ro/crate/1.1"
      },
      "about": {
        "@id": "./"
      }
    },
    {
      "@id": "file_1.txt",
      "@type": "File",
      "name": "Sample File",
      "contentSize": "156GB",
      "dmpDataNumber": {
        "@id": "#dmp:1"
      },
      "@context": "https://raw.githubusercontent.com/ascade/nii_dg/develop/schema/context/cao/File.json"
    },
    {
      "@id": "file_1.txt",
      "@type": "File",
      "name": "Sample File",
      "contentSize": "156GB",
      "experimentPackageFlag": true,
      "@context": "https://raw.githubusercontent.com/ascade/nii_dg/develop/schema/context/ginfork/File.json"
    },
    {
      "@id": "https://www.nii.ac.jp/",
      "@type": "HostingInstitution",
      "name": "National Institute of Informatics",
      "address": "Tokyo Japan",
      "@context": "https://raw.githubusercontent.com/ascade/nii_dg/develop/schema/context/base/HostingInstitution.json"
    },
    {
      "@id": "https://example.com/person",
      "@type": "Person",
      "name": "Ichiro Suzuki",
      "affiliation": {
        "@id": "https://www.nii.ac.jp/"
      },
      "email": "ichiro@example.com",
      "@context": "https://raw.githubusercontent.com/ascade/nii_dg/develop/schema/context/cao/Person.json"
    },
    {
      "@id": "https://example.com/repository",
      "@type": "RepositoryObject",
      "name": "sample repository",
      "@context": "https://raw.githubusercontent.com/ascade/nii_dg/develop/schema/context/base/RepositoryObject.json"
    },
    {
      "@id": "#dmp:1",
      "@type": "DMP",
      "name": "execution results",
      "description": "Files generated by execution of workflow.",
      "creator": [
        {
          "@id": "https://example.com/person"
        }
      ],
      "keyword": "Informatics",
      "accessRights": "metadata only access",
      "repository": {
        "@id": "https://example.com/repository"
      },
      "hostingInstitution": {
        "@id": "https://www.nii.ac.jp/"
      },
      "dataManager": {
        "@id": "https://example.com/person"
      },
      "dataNumber": 1,
      "@context": "https://raw.githubusercontent.com/ascade/nii_dg/develop/schema/context/cao/DMP.json"
    },
    {
      "@id": "#CAO-DMP",
      "@type": "DMPMetadata",
      "name": "CAO-DMP",
      "about": {
        "@id": "./"
      },
      "funder": {
        "@id": "https://www.nii.ac.jp/"
      },
      "keyword": "Informatics",
      "hasPart": [
        {
          "@id": "#dmp:1"
        }
      ],
      "@context": "https://raw.githubusercontent.com/ascade/nii_dg/develop/schema/context/cao/DMPMetadata.json"
    },
    {
      "@id": "#ginmonitoring:1",
      "@type": "GinMonitoring",
      "about": {
        "@id": "./"
      },
      "contentSize": "1TB",
      "workflowIdentifier": "basic",
      "datasetStructure": "with_code",
      "@context": "https://raw.githubusercontent.com/ascade/nii_dg/develop/schema/context/ginfork/GinMonitoring.json"
    }
  ]
}
"""
