RootDataEntity:
  "@id":
    expected_type: str
    example: ./
    description: Required. MUST be "./".
  name:
    expected_type: str
    example: Example Research Project
    description: Required. Title of the research project.
  description:
    expected_type: str
    example: This research project aims to reveal the effect of xxx.
    description: Optional. Description of the research project.
  funder:
    expected_type: List[Funder]
    example: '[{"@id": "https://ror.org/01b9y6c26"}]'
    description: Required. Funding agencies of the research project. MUST be an array of Funder entities.
  dateCreated:
    expected_type: str
    example: "2022-12-09T10:48:07.976+00:00"
    description: Required. MUST be a string in ISO 8601 date format and a timestamp down to milliseconds. The time zone is UTC. Indicates timestamp the RO-Crate itself was created.
  creator:
    expected_type: List[Creator]
    example: '[{"@id": "https://orcid.org/0000-0001-2345-6789"}]'
    description: Required. MUST be an array of Person entities. Indicates all data creators involved in this research project.
  repository:
    expected_type: RepositoryObject
    example: '{ "@id": "https://doi.org/xxxxxxxx" }'
    description: Can be added when all data set is managed in a single repository. Indicates repository where the data is managed.
  distribution:
    expected_type: DataDownload
    example: '{"@id": "https://zenodo.org/record/example"}'
    description: Optional. It can be added when access rights have "open access" and all open-access data set is available from a single URL. Indicates where the download URL of the data set.
  hasPart:
    expected_type: List[Union[Dataset, File]]
    example: '[{"@id": "config/"}, {"@id": "config/config.txt"}]'
    description: Required. MUST be an array of Dataset and File entities that indicate files and directories.
File:
  "@id":
    expected_type: str
    example: config/setting.txt
    description: Required. MUST be either a URI Path relative to the RO Crate root (stated in the identifier term of RootDataEntity) or an absolute URI. When the file is from outside the repository, @id SHOULD be directly downloadable by a simple retrieval (e.g., HTTP GET), permitting redirections and HTTP/HTTPS authentication. RO-Crate itself (ro-crate-metadata.json) is excluded.
  name:
    expected_type: str
    example: setting.txt
    description: Required. Indicates file name.
  dmpDataNumber:
    expected_type: DMP
    example: '{"@id": "#dmp:1"}'
    description: Required. MUST be a @id term from the DMP entity. Indicates data number in DMP this file is included in.
  contentSize:
    expected_type: str
    example: 1560B
    description: Required. MUST be an integer of file size with the suffix "B" as a unit, bytes. Be validated with the size listed in DMP.
  encodingFormat:
    expected_type: str
    example: text/plain
    description: Optional. MUST be MIME type. Indicates file format.
  url:
    expected_type: str
    example: https://github.com/username/repository/file
    description: Optional. MUST be a direct URL to the file.
  sdDatePublished:
    expected_type: str
    example: "2022-12-01"
    description: Required when the file is from outside the RO-Crate Root. Indicates the date the file was obtained. MUST be a string in ISO 8601 date format.
Dataset:
  "@id":
    expected_type: str
    example: config/
    description: Required. MUST be either a URI Path relative to the RO-Crate root (stated in the identifier term of RootDataEntity). MUST end with "/". Indicates the path to the directory.
  name:
    expected_type: str
    example: config
    description: Required. Indicates directory name.
  url:
    expected_type: str
    example: https://github.com/username/repository/directory
    description: Optional. MUST be a direct URL to the directory.
DMP:
  "@id":
    expected_type: str
    example: "#dmp:1"
    description: Required. MUST be data No. with the prefix "#dmp:". Indicates data No. in the DMP list.
  name:
    expected_type: str
    example: calculated data
    description: Required. Indicates data title in DMP.
  description:
    expected_type: str
    example: Result data calculated by Newton's method
    description: Required. Indicates data description in DMP.
  accessRights:
    expected_type: Literal["open access", "restricted access", "embargoed access", "metadata only access"]
    example: open access
    description: Required when all data sets have a common access right, they can be omitted instead of added to RootDataEntity. MUST choose one from the list, open access; restricted access; embargoed access; or metadata-only access. Indicate the availability of the data set.
  availabilityStarts:
    expected_type: str
    example: "2023-04-01"
    description: Required when accessRights has embargoed access. MUST be a string in ISO 8601 date format. Be verified that the value is the future than the time of verification.
  isAccessibleForFree:
    expected_type: bool
    example: "True"
    description: Required when accessRights has open access or restricted access. MUST be a boolean. True means the data set is free to access, while False means consideration. When access rights have open access, MUST be True.
  usageInfo:
    expected_type: str
    example: Contact data manager before usage of this data set.
    description: Optional. An explanation for citation.
  distribution:
    expected_type: DataDownload
    example: '{"@id": "https://zenodo.org/record/example"}'
    description: Required when accessRights has open access. When all open-access data set is available from a single URL, they can be omitted instead of added to RootDataEntity. Indicates where the download URL of the data set.
  contentSize:
    expected_type: Literal["1GB", "10GB", "100GB", "1TB", "1PB"]
    example: 100GB
    description: Optional. MUST choose one from 1GB, 10GB, 100GB, 1TB and 1PB.
Funder:
  "@id":
    expected_type: str
    example: https://ror.org/04ksd4g47
    description: Required. MUST be the URL of the organization and recommended ROR ID.
  name:
    expected_type: str
    example: National Institute of Informatics
    description: Required. Name of the funder.
  description:
    expected_type: str
    example: Japan's only general academic research institution seeking to create future value in the new discipline of informatics.
    description: Optional. Description of a funder.
Creator:
  "@id":
    expected_type: str
    example: https://orcid.org/0000-0001-2345-6789
    description: Required. MUST be the URL of a creator and recommended ORCID ID.
  name:
    expected_type: str
    example: Ichiro Suzuki
    description: Required. Name of a creator. MUST be in the order of first name, and family name.
  alias:
    expected_type: str
    example: S. Ichiro
    description: Optional. Another writing of the name of a creator.
  affiliation:
    expected_type: Affiliation
    example: '{"@id": "https://ror.org/04ksd4g47"}'
    description: Required. Affiliation, a creator, belongs to. MUST be a @id term from the DMP entity.
  email:
    expected_type: str
    example: ichiro@example.com
    description: Required. Email address of the creator.
  telephone:
    expected_type: str
    example: "03-0000-0000"
    description: Optional. Phone number of the creator.
Affiliation:
  "@id":
    expected_type: str
    example: https://ror.org/04ksd4g47
    description: Required. MUST be the URL of the organization and recommended ROR ID.
  name:
    expected_type: str
    example: National Institute of Informatics
    description: Required. Name of the organization.
  description:
    expected_type: str
    example: Japan's only general academic research institution seeking to create future value in the new discipline of informatics.
    description: Optional. Description of the organization.
RepositoryObject:
  "@id":
    expected_type: str
    example: "https://doi.org/xxxxxxxx"
    description: Required. MUST be the URL of the repository. DOI link is recommended.
  name:
    expected_type: str
    example: Gakunin RDM
    description: Required. Name of a repository.
  description:
    expected_type: str
    example: Repository managed by NII.
    description: Optional. Description of a repository.
DataDownload:
  "@id":
    expected_type: str
    example: https://rdm.nii.ac.jp/example/
    description: Required. MUST be a reachable URL.
  downloadUrl:
    expected_type: str
    example: https://zenodo.org/record/example
    description: Required. URL for downloading data sets. MUST be the same URL as the @id term.
HostingInstitution:
  "@id":
    expected_type: str
    example: https://ror.org/04ksd4g47
    description: Required. MUST be the URL of the organization and recommended ROR ID.
  name:
    expected_type: str
    example: National Institute of Informatics
    description: Required. Name of the organization.
  description:
    expected_type: str
    example: Japan's only general academic research institution seeking to create future value in the new discipline of informatics.
    description: Optional. Description of the organization.
  address:
    expected_type: str
    example: "2-1-2 Hitotsubashi, Chiyoda-ku, Tokyo, Japan, 101-8430"
    description: Required. Physical address of the organization.
