RootDataEntity:
  '@id':
    expected_type: str
    example: ./
    description: Required. MUST be `./`.
  name:
    expected_type: str
    example: Example Research Project
    description: Required. Title of the research project.
  description:
    expected_type: str
    example: This research project aims to reveal the effect of xxx.
    description: Optional. Description of the research project.
  funder:
    expected_type: List[Organization]
    example: '[{"@id": "https://ror.org/01b9y6c26"}]'
    description: Required. Funding agencies of the research project. MUST be an array of @id term of Organization entity.
  dateCreated:
    expected_type: str
    example: '2022-12-09T10:48:07.976+00:00'
    description: Required. MUST be a string in ISO 8601 date format and a timestamp down to milliseconds. The time zone is UTC. Indicates timestamp the RO-Crate itself was created.
  creator:
    expected_type: List[Person]
    example: '[{"@id": "https://orcid.org/0000-0001-2345-6789"}]'
    description: Required. MUST be an array of @id term of Person entity. Indicates all data creators involved in this research project.
  repository:
    expected_type: RepositoryObject
    example: '{ "@id": "https://doi.org/xxxxxxxx" }'
    description: Can be added when all data set is managed in a single repository. MUST be @id term of RepositoryObject entity. Indicates repository where the data is managed.
  distribution:
    expected_type: DataDownload
    example: '{"@id": "https://zenodo.org/record/example"}'
    description: Can be added when access rights have `open access` and all open-access data set is available from a single URL. MUST be @id term of DataDownload entity. Indicates where the download URL of the data set.
  hasPart:
    expected_type: List[Union[Dataset, File]]
    example: '[{"@id": "config/"}, {"@id": "config/config.txt"}]'
    description: Required. MUST be an array of Dataset and File entities that indicate files and directories as subjects of data governance.
File:
  '@id':
    expected_type: str
    example: config/setting.txt
    description: Required. MUST be either a URI Path relative to the top directory of your repository (stated in the identifier term of RootDataEntity) or an absolute URI. When the file is from outside the repository, @id SHOULD be directly downloadable by a simple retrieval (e.g., HTTP GET), permitting redirections and HTTP/HTTPS authentication. RO-Crate itself (ro-crate-metadata.json) is excluded.
  name:
    expected_type: str
    example: setting.txt
    description: Required. Indicates the file name.
  dmpDataNumber:
    expected_type: DMP
    example: '{"@id": "#dmp:1"}'
    description: Required. MUST be @id term of the DMP entity. Indicates data number in DMP that includes this file.
  contentSize:
    expected_type: str
    example: 1560B
    description: Required. MUST be an integer of the file size with the suffix `B` as a unit, bytes. It will be used in the validation of the size listed in DMP.
  encodingFormat:
    expected_type: str
    example: text/plain
    description: Optional. MUST be MIME type. Indicates file format.
  sha256:
    expected_type: str
    example: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
    description: Optional. MUST be the SHA-2 SHA256 hash of the file.
  url:
    expected_type: str
    example: https://github.com/username/repository/file
    description: Optional. MUST be a direct URL to the file.
  sdDatePublished:
    expected_type: str
    example: '2022-12-01'
    description: Required when the file is from outside the RO-Crate Root. Indicates the date that the file was obtained. MUST be a string in ISO 8601 date format.
Dataset:
  '@id':
    expected_type: str
    example: config/
    description: Required. MUST be either a URI Path relative to the RO-Crate root (stated in the identifier term of RootDataEntity) or an absolute URI. MUST end with `/`. Indicates the path to the directory.
  name:
    expected_type: str
    example: config
    description: Required. Indicates directory name.
  url:
    expected_type: str
    example: https://github.com/username/repository/directory
    description: Optional. MUST be a direct URL to the directory.
DMP:
  '@id':
    expected_type: str
    example: '#dmp:1'
    description: Required. MUST be data No. with the prefix `#dmp:`. Indicates data No. in the DMP list.
  name:
    expected_type: str
    example: calculated data
    description: Required. Indicates data title in DMP.
  description:
    expected_type: str
    example: Result data calculated by Newton's method
    description: Required. Indicates data description in DMP.
  accessRights:
    expected_type: Literal["open access", "restricted access", "embargoed access", "metadata only access"]
    example: open access
    description: Required. MUST choose one from `open access`, `restricted access`, `embargoed access` and `metadata-only access`. Indicate the availability of the data set.
  availabilityStarts:
    expected_type: str
    example: '2023-04-01'
    description: Required when accessRights has `embargoed access`. MUST be a string in ISO 8601 date format. It will be verified in DG-Core that the value is the future than the time of verification.
  isAccessibleForFree:
    expected_type: bool
    example: 'True'
    description: Required when accessRights has `open access` or `restricted access`. MUST be a boolean. True means the data set is free to access, while False means consideration. When access rights have open access, MUST be True.
  usageInfo:
    expected_type: str
    example: Contact data manager before usage of this data set.
    description: Optional. An explanation for citation.
  repository:
    expected_type: RepositoryObject
    example: '{ "@id": "https://doi.org/xxxxxxxx" }'
    description: Required. MUST be @id term of the RepositoryObject entity. When all data set is managed in a single repository, it can be omitted instead of adding to RootDataEntity. Indicates repository where the data is managed.
  distribution:
    expected_type: DataDownload
    example: '{"@id": "https://zenodo.org/record/example"}'
    description: Required when accessRights has `open access`. MUST be @id term of the DataDownload entity. When all open-access data set is available from a single URL, they can be omitted instead of added to RootDataEntity. Indicates where the download URL of the data set.
  contentSize:
    expected_type: Literal["1GB", "10GB", "100GB", "over100GB"]
    example: 100GB
    description: Optional. MUST choose one from `1GB`, `10GB`, `100GB` and `over100GB`. Indicates maximum of sum total file size included in this DMP condition.
Organization:
  '@id':
    expected_type: str
    example: https://ror.org/04ksd4g47
    description: Required. MUST be the URL of the organization. ROR ID is recommended.
  name:
    expected_type: str
    example: National Institute of Informatics
    description: Required. Name of the organization.
  description:
    expected_type: str
    example: Japan's only general academic research institution seeking to create future value in the new discipline of informatics.
    description: Optional. Description of the organization.
Person:
  '@id':
    expected_type: str
    example: https://orcid.org/0000-0001-2345-6789
    description: Required. MUST be URL of the person. ORCID ID is recommended.
  name:
    expected_type: str
    example: Ichiro Suzuki
    description: Required. Name of the person. MUST be in the order of first name, and family name.
  alias:
    expected_type: str
    example: S. Ichiro
    description: Optional. Another writing of a name of the person.
  affiliation:
    expected_type: Organization
    example: '{"@id": "https://ror.org/04ksd4g47"}'
    description: Required. Affiliation which the person belongs to. MUST be a @id term of the DMP entity.
  email:
    expected_type: str
    example: ichiro@example.com
    description: Required. Email address of the person.
  telephone:
    expected_type: str
    example: '03-0000-0000'
    description: Optional. Phone number of the person.
License:
  '@id':
    expected_type: str
    example: 'https://www.apache.org/licenses/LICENSE-2.0'
    description: Required. MUST be URL of the license.
  name:
    expected_type: str
    example: Apache License 2.0
    description: Required. Name of the license.
  description:
    expected_type: str
    example: the licensed defined by Apache Software Foundation
    description: Optional. Description of the license.
RepositoryObject:
  '@id':
    expected_type: str
    example: 'https://doi.org/xxxxxxxx'
    description: Required. MUST be URL of the repository. DOI link is recommended.
  name:
    expected_type: str
    example: Gakunin RDM
    description: Required. Indicates a name of the repository.
  description:
    expected_type: str
    example: Repository managed by NII.
    description: Optional. Indicates a description of the repository.
DataDownload:
  '@id':
    expected_type: str
    example: https://zenodo.org/record/example
    description: Required. MUST be a reachable URL.
  description:
    expected_type: str
    example: All data set is available from this URL as a zip file.
    description: Optional. Indicates a description of the download.
  sha256:
    expected_type: str
    example: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
    description: Optional. MUST be the SHA-2 SHA256 hash of the download file.
  uploadDate:
    expected_type: str
    example: '2022-12-01'
    description: Optional. MUST be a string in ISO 8601 date format. Indicates the date when this data set was uploaded to this site.
HostingInstitution:
  # based on Organization entity
  '@id':
    expected_type: str
    example: https://ror.org/04ksd4g47
    description: Required. MUST be the URL of the organization. ROR ID is recommended.
  name:
    expected_type: str
    example: National Institute of Informatics
    description: Required. Name of the organization.
  description:
    expected_type: str
    example: Japan's only general academic research institution seeking to create future value in the new discipline of informatics.
    description: Optional. Description of the organization.
  address:
    expected_type: str
    example: '2-1-2 Hitotsubashi, Chiyoda-ku, Tokyo, Japan, 101-8430'
    description: Required. Physical address of the organization.
PropertyValue:
  '@id':
    expected_type: str
    example: '#jRCT:1234567'
    description: Required. URL of registrated data. When there is no URL, combine registry name and ID with prefix `#`.
  name:
    expected_type: str
    example: Japan Registry of Clinical Trials
    description: Required. Name of the data registry service.
  value:
    expected_type: str
    example: '1234567'
    description: Required. Indicates ID you got from the registry service.
ContactPoint:
  '@id':
    expected_type: str
    example: '#mailto:contact@example.com'
    description: Required. MUST be email with the prefix `#mailto:` or be phone number with the prefix `#callto:`.
  name:
    expected_type: str
    example: Sample Inc., Open-Science department, data management unit
    description: Required. Name of a person or a department in charge of managing data set.
  email:
    expected_type: str
    example: contact@example.com
    description: Required either email or telephone (described in the next section). Email address as contact information.
  telephone:
    expected_type: str
    example: '03-0000-0000'
    description: Required either email (described in the previous section) or telephone. Phone number as contact information.
