RootDataEntity:
  "@id":
    description: Required. Must be "./" .
    example: ./
    expected_type: str
  name:
    description: Required. Title of the research project
    example: Sample Research
    expected_type: str
  description:
    description: Optional. Description of the research project
    example: This research project aims to reveal the affect of xxx.
    expected_type: str
  funder:
    description: Required. Funding agencies of research project. Must be array of Funder entities.
    example:
      [
        { "@id": "https://ror.org/04ksd4g47" },
        { "@id": "https://ror.org/007f5s288" }
      ]
    expected_type: List[Funder]
  dmpFormat:
    description: Required. Indicates format of data management plan. Must choose one from the list, common metadata; AMED; METI.
    example: AMED
    expected_type: Literal["common metadata", "AMED", "METI"]
  identifier:
    description: Optional. Must be array of PropertyValue entities. Indicates e-Rad project ID and any other identifier.
    example: [{ "@id": "#e-Rad:123456" }]
    expected_type: List[PropertyValue]
  dateCreated:
    description:
      Required. MUST be a string in ISO 8601 date format and a timestamp down to
      the millisecond. Time zone is in UTC. Indicates timestamp the RO-Crate itself is created.
    example: "2022-12-09T10:48:07.976+00:00"
    expected_type: str
  creator:
    description: Required. Must be array of Person entities. Indicates all data creators involved in this research project.
    example: [{ "@id": "https://orcid.org/0000-0001-2345-6789" }]
    expected_type: List[Creator]
  maintainer:
    description: Optional. Can be added when all data in DMP list is managed by single instituion or a data manager. Indicates hosting institution and data manager.
    example:
      [
        { "@id": "https://ror.org/04ksd4g47" },
        { "@id": "https://orcid.org/0000-0001-2345-6789" }
      ]
    expected_type: List[HostingInstituion | DataManager]
  repository:
    description: Optional. Can be added when all data set is managed in a single repository. Indicates where the data is managed.
    example: { "@id": "https://github.com/username/repository" }
    expected_type: RepositoryObject
  distribution:
    description: Optional. Can be added when access rights has "open access" and all open-access data set is available from a single URL. Indicates where download url of data set.
    example: { "@id": "https://zenodo.org/record/example" }
    expected_type: DataDownload
  hasPart:
    description: Required. Must be array of Dataset and File entities which indicate files and directories.
    example: [{ "@id": "config/" }, { "@id": "config/config.txt" }]
    expected_type: List[Dataset | File]
File:
  "@id":
    required: MUST
    rule:
      MUST be either a URI Path relative to the RO Crate root (stated in identifier
      term of RootDataEntity) or an absolute URI.  When the file from outside of the
      repository, @id SHOULD be directly downloadable by a simple retrieval (e.g.
      HTTP GET), permitting redirections and HTTP/HTTPS authentication.
    description: Path of the file
  name:
    required: MUST
    rule: string
    description: Title of the file
  dmpDataNumber:
    required: MUST
    rule: 'Object of @id term from DMP Entity, e.g. "{"@id": "#dmp:1"}".'
    description: Corresponding data number of DMP
  contentSize:
    required: MUST
    rule:
      Integer plus "B" as units, e.g. "1560B". Be validated with the size listed
      in the DMP.
    description: File size
  encodingFormat:
    required: MAY
    rule: MUST be MIME type, e.g. "application/pdf".
    description: File Format
  url:
    required: MAY
    rule: URL
    description: Direct URL to the file
  sdDatePublished:
    required: MUST if the file from outside the RO-Crate Root
    rule: MUST be a string in ISO 8601 date format
    description: Date the file was obtained
Dataset:
  "@id":
    required: MUST
    rule:
      MUST be either a URI Path relative to the RO Crate root (stated in identifier
      term of RootDataEntity). SHOULD end with "/".
    description: Path of the directory
  name:
    required: MUST
    rule: string
    description: Title of the directory
  dmpDataNumber:
    required: MAY
    rule: 'Object of @id term from DMP entity, e.g. "{"@id": "#dmp:1"}".'
    description: Corresponding data number of DMP
  contentSize:
    required: MAY
    rule:
      Integer plus "B" as units, e.g. "1560B". Be validated with the size listed
      in the DMP.
    description: Total file size under the directory
  url:
    required: MAY
    rule: URL
    description: Direct URL to the directory
DMP:
  "@id":
    required: MUST
    rule: Data No. with prefix "#dmp:", e.g. "#dmp:1".
    description: Data Number in DMP
  name:
    required: MUST
    rule: string
    description: Data title in DMP
  description:
    required: MUST
    rule: string
    description: Description of data in DMP
  accessRights:
    description: Required. When all data set have common access right, it can be ommited instead of added to RootDataEntity. Must choose one from the list, open access; restricted access; embargoed access; metadata only access. Indicate the availability of data set.
    example: open access
    expected_type: Literal["open access", "restricted access", "embargoed access", "metadata only access"]
  availableStarts:
    required: MUST if accessRights has embargoed access
    rule:
      MUST be a string in ISO 8601 date format. Be velified that the value(ISO
      date) is the future than the time of verification.
    description: When the data will be available (open access)
  usageInfo:
    required: MAY
    rule: string
    description: Explanation for citaion
  distribution:
    required: MUST if accessRights has open access and different for each data set.
    rule: 'Object of @id term from DataDownload entity, e.g. "{"@id": "https://example.com/downloadlink"}".'
    description: Download link of dataset
  contentSize:
    required: MAY
    rule:
      Integer plus "B" as units, e.g. "1560B". Be validated with the size listed
      in the DMP.
    description: Total file size under the directory
