RootDataEntity:
  "@id":
    description: Required. Must be "./" .
    example: ./
    expected_type: str
  name:
    description: Required. Title of the research project
    example: Sample Research
    expected_type: str
  description:
    description: Optional. Description of the research project
    example: This research project aims to reveal the affect of xxx.
    expected_type: str
  funder:
    description: Required. Funding agencies of research project. Must be array of Funder entities.
    example: '[
      { "@id": "https://ror.org/04ksd4g47" },
      { "@id": "https://ror.org/007f5s288" }
      ]'
    expected_type: List[Funder]
  dateCreated:
    description: Required. MUST be a string in ISO 8601 date format and a timestamp down to the millisecond. Time zone is in UTC. Indicates timestamp the RO-Crate itself is created.
    example: "2022-12-09T10:48:07.976+00:00"
    expected_type: str
  creator:
    description: Required. Must be array of Person entities. Indicates all data creators involved in this research project.
    example: '[{ "@id": "https://orcid.org/0000-0001-2345-6789" }]'
    expected_type: List[Creator]
  repository:
    description: Optional. Can be added when all data set is managed in a single repository. Indicates where the data is managed.
    example: '{ "@id": "https://github.com/username/repository" }'
    expected_type: RepositoryObject
  distribution:
    description: Optional. Can be added when access rights has "open access" and all open-access data set is available from a single URL. Indicates where download url of data set.
    example: '{ "@id": "https://zenodo.org/record/example" }'
    expected_type: DataDownload
  hasPart:
    description: Required. Must be array of Dataset and File entities which indicate files and directories.
    example: '[{ "@id": "config/" }, { "@id": "config/config.txt" }]'
    expected_type: List[Dataset | File]
File:
  "@id":
    description: Required. MUST be either a URI Path relative to the RO Crate root (stated in identifier term of RootDataEntity) or an absolute URI. When the file from outside of the repository, @id SHOULD be directly downloadable by a simple retrieval (e.g. HTTP GET), permitting redirections and HTTP/HTTPS authentication. RO-Crate itself (ro-crate-metadata.json) is excluded.
    example: config/setting.txt
    expected_type: str
  name:
    description: Required. Indicates file name.
    example: setting.txt
    expected_type: str
  dmpDataNumber:
    description: Required. Must be @id term from DMP entity. Indicates data number in DMP this file is included in.
    example: '{ "@id": "#dmp:1" }'
    expected_type: DMP
  contentSize:
    description: Required. Must be integer of file size with a suffix "B" as a unit, bite. Be validated with the size listed in DMP.
    example: 1560B
    expected_type: str
  encodingFormat:
    description: Optional. Must be MIME type. Indicates file format.
    example: text/plain
    expected_type: str
  url:
    description: Optional. Must be direct URL to the file.
    example: https://github.com/username/repository/file
    expected_type: str
  sdDatePublished:
    description: Required when the file from outside the RO-Crate Root. Indicates date the file was obtained. MUST be a string in ISO 8601 date format.
    example: "2022-12-01"
    expected_type: datetime
Dataset:
  "@id":
    description: Required. MUST be either a URI Path relative to the RO Crate root (stated in identifier term of RootDataEntity). Must end with "/". Indicats path to the directory.
    example: config/
    expected_type: str
  name:
    description: Required. Indicates directory name.
    example: config
    expected_type: str
  url:
    description: Optional. Must be direct URL to the directory.
    example: https://github.com/username/repository/directory
    expected_type: str
DMP:
  "@id":
    description: Required. Must be data No. with prefix "#dmp:". Indicates data No. in DMP list.
    example: "#dmp:1"
    expected_type: str
  name:
    description: Required. Indicates data title in DMP.
    example: calculated data
    expected_type: str
  description:
    description: Required. Indicates data description in DMP.
    example: Result data calculated by Newton's method
    expected_type: str
  accessRights:
    description: Required. When all data set have common access right, it can be ommited instead of added to RootDataEntity. Must choose one from the list, open access; restricted access; embargoed access; metadata only access. Indicate the availability of data set.
    example: open access
    expected_type: Literal["open access", "restricted access", "embargoed access", "metadata only access"]
  availabilityStarts:
    description: Required when accessRights has embargoed access. MUST be a string in ISO 8601 date format. Be velified that the value is the future than the time of verification.
    example: "2023-04-01"
    expected_type: datetime
  isAccessibleForFree:
    description: Required when accessRights has open access or restricted access. MUST be a boolean. True means data set is free to access, while False means consideration. When access rights has open access, must be True.
    example: "True"
    expected_type: bool
  usageInfo:
    description: Optional. Explanation for citaion.
    example: Contact data manager before usage of this data set.
    expected_type: str
  distribution:
    description: Required when accessRights has open access. When all open-access data set is available from a single URL, it can be ommited instead of adding to RootDataEntity. Indicates where download url of data set.
    example: '{ "@id": "https://zenodo.org/record/example" }'
    expected_type: DataDownload
  contentSize:
    description: Optional. Must choose one from the list, 1GB; 10GB; 100GB; 1TB; 1PB.
    example: 100GB
    expected_type: Literal["1GB", "10GB", "100GB", "1TB", "1PB"]
Funder:
  "@id":
    description: Required. Must be URL of the organization and recommended ROR ID.
    example: https://ror.org/04ksd4g47
    expected_type: str
  name:
    description: Required. Name of the funder.
    example: National Institute of Informatics
    expected_type: str
  description:
    description: Optional. Description of funder.
    example: Japan's only general academic research institution seeking to create future value in the new discipline of informatics.
    expected_type: str
Creator:
  "@id":
    description: Required. Must be URL of a creator and recommended ORCID ID.
    example: https://orcid.org/0000-0001-2345-6789
    expected_type: str
  name:
    description: Required. Name of a creator. Must be in order of first name, family name.
    example: Ichiro Suzuki
    expected_type: str
  alias:
    description: Optional. Another writings of the name of a creator.
    example: イチロー
    expected_type: str
  affiliation:
    description: Required. Affiliation a creator belongs to. Must be @id term from DMP entity.
    example: '{ "@id": "https://ror.org/04ksd4g47" }'
    expected_type: Affiliation
  email:
    description: Required. Email address of a creator.
    example: ichiro@example.com
    expected_type: str
Affiliation:
  "@id":
    description: Required. Must be URL of the organization and recommended ROR ID.
    example: https://ror.org/04ksd4g47
    expected_type: str
  name:
    description: Required. Name of an organization.
    example: National Institute of Informatics
    expected_type: str
  description:
    description: Optional. Description of an organization.
    example: Japan's only general academic research institution seeking to create future value in the new discipline of informatics.
    expected_type: str
RepositoryObject:
  "@id":
    description: Required. Must be URL of a repository.
    example: https://rdm.nii.ac.jp/example/
    expected_type: str
  name:
    description: Required. Name of a repository.
    example: Gakunin RDM
    expected_type: str
  description:
    description: Optional. Description of a repository.
    example: Repository managed by NII.
    expected_type: str
DataDownload:
  "@id":
    description: Required. Must be reachable URL.
    example: https://rdm.nii.ac.jp/example/
    expected_type: str
  downloadUrl:
    description: Required. URL for donwloding data set. Must be the same URL as @id term.
    example: https://zenodo.org/record/example
    expected_type: str
