name: flake8

on:
  push:
    branches:
      - main
  workflow_dispatch: {}
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  flake8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/setup.py') }}
      - name: Install dependencies
        run: |
          python3 -m pip install --no-cache-dir --progress-bar off -U pip setuptools wheel
          python3 -m pip install --no-cache-dir --progress-bar off -U .[tests]
      - name: Check with flake8
        run: |
          bash ./tests/lint_and_style_check/flake8.sh
